version: '2'
services:

  strapi:
    build: .
    depends_on:
    - mongo-strapi
    image: wulpers-strapi
    ports:
    - "1337:1337"
    expose:
    - "1337"
    # command: sh 
    volumes:
    - ./project:/srv/app
    networks:
    - strapi
    env_file:
    - .env

  mongo-strapi:
    image: mongo:latest
    volumes:
    - ./mongodb:/data/db
    - ./mongodb_config:/data/configdb
    ports: 
    - "27018:27017"
    expose:
    - "27017"
    networks:
    - strapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: strapi

networks:
  strapi:
    driver: bridge
