version: '2'
services:

  strapi:
    image: strapi/strapi:latest
    depends_on:
    - postgres
    ports:
    - "1337:1337"
    expose:
    - "1337"
    volumes:
    - ./strapi:/srv/app
    networks:
    - strapi
    env_file:
    - .env

  front:
    image: node:latest
    depends_on:
    - strapi
    - postgres
    ports:
    - "3000:3000"
    expose:
    - "3000"
    working_dir: /var/app/
    volumes:
    - ./frontend/:/var/app
    command: npm install
    command: npm run dev
    networks:
    - strapi
    env_file:
    - .env

  postgres:
    image: postgres:latest
    volumes:
    - ./postgres:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    networks:
    - strapi
    env_file:
    - .env

  nginx:
    image: nginx:latest
    depends_on:
    - postgres
    - strapi
    - front
    volumes:
    - ./nginx:/etc/nginx
    ports: 
    - ${PORT_FRONT}
    - ${PORT_STRAPI}
    expose:
    - ${PORT_FRONT_EXPOSE}
    - ${PORT_STRAPI_EXPOSE}
    networks:
    - strapi
    env_file:
    - .env

networks:
  strapi:
    driver: bridge
