version: '2'
services:

  strapi:
    image: strapi/strapi:latest
    depends_on:
    - mongo-strapi
    ports:
    - "1337:1337"
    expose:
    - "1337"
    volumes:
    - ./strapi:/srv/app
    networks:
    - strapi
    env_file:
    - .env

  front:
    image: node:latest
    depends_on:
    - strapi
    - mongo-strapi
    ports:
    - "3000:3000"
    expose:
    - "3000"
    working_dir: /var/app/
    volumes:
    - ./frontend/:/var/app
    command: npm start
    networks:
    - strapi
    env_file:
    - .env

  mongo-strapi:
    image: mongo:latest
    volumes:
    - ./mongodb:/data/db
    ports: 
    - "27018:27017"
    expose:
    - "27017"
    networks:
    - strapi
    env_file:
    - .env

networks:
  strapi:
    driver: bridge
